ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CLERK';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'PEACE_AND_ORDER';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'PUNONG_BARANGAY';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'SK';
